# Generated by Django 5.1.2 on 2024-11-02 12:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='resultmodel',
            old_name='field',
            new_name='lessons',
        ),
        migrations.RemoveField(
            model_name='useractivitysuggestion',
            name='motivation_level',
        ),
        migrations.RemoveField(
            model_name='useractivitysuggestion',
            name='study_method',
        ),
    ]
