# Generated by Django 5.1.2 on 2024-11-03 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_remove_useractivitysuggestion_sleep_hours'),
    ]

    operations = [
        migrations.CreateModel(
            name='YKSExamResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('program_code', models.CharField(max_length=100)),
                ('university_type', models.CharField(max_length=100)),
                ('university_name', models.CharField(max_length=255)),
                ('faculty_name', models.CharField(max_length=255)),
                ('program_name', models.CharField(max_length=255)),
                ('score_type', models.CharField(max_length=50)),
                ('kontenjan_0', models.IntegerField(blank=True, null=True)),
                ('yerlesen_0', models.IntegerField(blank=True, null=True)),
                ('min_score_0', models.FloatField(blank=True, null=True)),
                ('max_score_0', models.FloatField(blank=True, null=True)),
                ('kontenjan_1', models.IntegerField(blank=True, null=True)),
                ('yerlesen_1', models.IntegerField(blank=True, null=True)),
                ('min_score_1', models.FloatField(blank=True, null=True)),
                ('max_score_1', models.FloatField(blank=True, null=True)),
                ('kontenjan_2', models.IntegerField(blank=True, null=True)),
                ('yerlesen_2', models.IntegerField(blank=True, null=True)),
                ('min_score_2', models.FloatField(blank=True, null=True)),
                ('max_score_2', models.FloatField(blank=True, null=True)),
                ('kontenjan_3', models.IntegerField(blank=True, null=True)),
                ('yerlesen_3', models.IntegerField(blank=True, null=True)),
                ('min_score_3', models.FloatField(blank=True, null=True)),
                ('max_score_3', models.FloatField(blank=True, null=True)),
                ('kontenjan_4', models.IntegerField(blank=True, null=True)),
                ('yerlesen_4', models.IntegerField(blank=True, null=True)),
                ('min_score_4', models.FloatField(blank=True, null=True)),
                ('max_score_4', models.FloatField(blank=True, null=True)),
            ],
        ),
    ]
