# Generated by Django 5.1.2 on 2024-11-03 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_rename_kontenjan_0_yksexamresult_kontenjan_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='yksexamresult',
            name='kontenjan',
        ),
        migrations.RemoveField(
            model_name='yksexamresult',
            name='max_score',
        ),
        migrations.RemoveField(
            model_name='yksexamresult',
            name='min_score',
        ),
        migrations.RemoveField(
            model_name='yksexamresult',
            name='year',
        ),
        migrations.RemoveField(
            model_name='yksexamresult',
            name='yerlesen',
        ),
        migrations.AddField(
            model_name='yksexamresult',
            name='kontenjan_5',
            field=models.IntegerField(blank=True, null=True, verbose_name='Kontenjan.4'),
        ),
        migrations.AddField(
            model_name='yksexamresult',
            name='max_score_5',
            field=models.FloatField(blank=True, null=True, verbose_name='En Büyük Puan.4'),
        ),
        migrations.AddField(
            model_name='yksexamresult',
            name='min_score_5',
            field=models.FloatField(blank=True, null=True, verbose_name='En Küçük Puan.4'),
        ),
        migrations.AddField(
            model_name='yksexamresult',
            name='yerlesen_5',
            field=models.IntegerField(blank=True, null=True, verbose_name='Yerleşen.4'),
        ),
        migrations.AlterField(
            model_name='yksexamresult',
            name='faculty_name',
            field=models.CharField(max_length=255, verbose_name='Fakülte/Yüksekokul Adı'),
        ),
        migrations.AlterField(
            model_name='yksexamresult',
            name='kontenjan_1',
            field=models.IntegerField(blank=True, null=True, verbose_name='Kontenjan'),
        ),
        migrations.AlterField(
            model_name='yksexamresult',
            name='kontenjan_2',
            field=models.IntegerField(blank=True, null=True, verbose_name='Kontenjan.1'),
        ),
        migrations.AlterField(
            model_name='yksexamresult',
            name='kontenjan_3',
            field=models.IntegerField(blank=True, null=True, verbose_name='Kontenjan.2'),
        ),
        migrations.AlterField(
            model_name='yksexamresult',
            name='kontenjan_4',
            field=models.IntegerField(blank=True, null=True, verbose_name='Kontenjan.3'),
        ),
        migrations.AlterField(
            model_name='yksexamresult',
            name='max_score_1',
            field=models.FloatField(blank=True, null=True, verbose_name='En Büyük Puan'),
        ),
        migrations.AlterField(
            model_name='yksexamresult',
            name='max_score_2',
            field=models.FloatField(blank=True, null=True, verbose_name='En Büyük Puan.1'),
        ),
        migrations.AlterField(
            model_name='yksexamresult',
            name='max_score_3',
            field=models.FloatField(blank=True, null=True, verbose_name='En Büyük Puan.2'),
        ),
        migrations.AlterField(
            model_name='yksexamresult',
            name='max_score_4',
            field=models.FloatField(blank=True, null=True, verbose_name='En Büyük Puan.3'),
        ),
        migrations.AlterField(
            model_name='yksexamresult',
            name='min_score_1',
            field=models.FloatField(blank=True, null=True, verbose_name='En Küçük Puan'),
        ),
        migrations.AlterField(
            model_name='yksexamresult',
            name='min_score_2',
            field=models.FloatField(blank=True, null=True, verbose_name='En Küçük Puan.1'),
        ),
        migrations.AlterField(
            model_name='yksexamresult',
            name='min_score_3',
            field=models.FloatField(blank=True, null=True, verbose_name='En Küçük Puan.2'),
        ),
        migrations.AlterField(
            model_name='yksexamresult',
            name='min_score_4',
            field=models.FloatField(blank=True, null=True, verbose_name='En Küçük Puan.3'),
        ),
        migrations.AlterField(
            model_name='yksexamresult',
            name='program_code',
            field=models.CharField(max_length=100, verbose_name='Program Kodu'),
        ),
        migrations.AlterField(
            model_name='yksexamresult',
            name='program_name',
            field=models.CharField(max_length=255, verbose_name='Program Adı'),
        ),
        migrations.AlterField(
            model_name='yksexamresult',
            name='score_type',
            field=models.CharField(max_length=50, verbose_name='Puan Türü'),
        ),
        migrations.AlterField(
            model_name='yksexamresult',
            name='university_name',
            field=models.CharField(max_length=255, verbose_name='Üniversite Adı'),
        ),
        migrations.AlterField(
            model_name='yksexamresult',
            name='university_type',
            field=models.CharField(max_length=100, verbose_name='Üniversite Türü'),
        ),
        migrations.AlterField(
            model_name='yksexamresult',
            name='yerlesen_1',
            field=models.IntegerField(blank=True, null=True, verbose_name='Yerleşen'),
        ),
        migrations.AlterField(
            model_name='yksexamresult',
            name='yerlesen_2',
            field=models.IntegerField(blank=True, null=True, verbose_name='Yerleşen.1'),
        ),
        migrations.AlterField(
            model_name='yksexamresult',
            name='yerlesen_3',
            field=models.IntegerField(blank=True, null=True, verbose_name='Yerleşen.2'),
        ),
        migrations.AlterField(
            model_name='yksexamresult',
            name='yerlesen_4',
            field=models.IntegerField(blank=True, null=True, verbose_name='Yerleşen.3'),
        ),
    ]
