# Generated by Django 5.1.2 on 2024-12-13 23:34

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_alter_yksexamresult_university_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usermodel',
            name='daily_report_list_ayt',
        ),
        migrations.RemoveField(
            model_name='dailyreportmodeltyt',
            name='daily_list',
        ),
        migrations.RemoveField(
            model_name='usermodel',
            name='daily_report_list_tyt',
        ),
        migrations.RemoveField(
            model_name='exammodel',
            name='result_list',
        ),
        migrations.RemoveField(
            model_name='useractivitysuggestion',
            name='birth_date',
        ),
        migrations.RemoveField(
            model_name='useractivitysuggestion',
            name='daily_study_hours',
        ),
        migrations.RemoveField(
            model_name='useractivitysuggestion',
            name='goals',
        ),
        migrations.RemoveField(
            model_name='useractivitysuggestion',
            name='gpa',
        ),
        migrations.RemoveField(
            model_name='useractivitysuggestion',
            name='name',
        ),
        migrations.RemoveField(
            model_name='useractivitysuggestion',
            name='study_field',
        ),
        migrations.RemoveField(
            model_name='useractivitysuggestion',
            name='surname',
        ),
        migrations.RemoveField(
            model_name='useractivitysuggestion',
            name='uid',
        ),
        migrations.RemoveField(
            model_name='yksexamresult',
            name='kontenjan_1',
        ),
        migrations.RemoveField(
            model_name='yksexamresult',
            name='kontenjan_2',
        ),
        migrations.RemoveField(
            model_name='yksexamresult',
            name='kontenjan_3',
        ),
        migrations.RemoveField(
            model_name='yksexamresult',
            name='kontenjan_4',
        ),
        migrations.RemoveField(
            model_name='yksexamresult',
            name='kontenjan_5',
        ),
        migrations.RemoveField(
            model_name='yksexamresult',
            name='max_score_1',
        ),
        migrations.RemoveField(
            model_name='yksexamresult',
            name='max_score_2',
        ),
        migrations.RemoveField(
            model_name='yksexamresult',
            name='max_score_3',
        ),
        migrations.RemoveField(
            model_name='yksexamresult',
            name='max_score_4',
        ),
        migrations.RemoveField(
            model_name='yksexamresult',
            name='max_score_5',
        ),
        migrations.RemoveField(
            model_name='yksexamresult',
            name='min_score_1',
        ),
        migrations.RemoveField(
            model_name='yksexamresult',
            name='min_score_2',
        ),
        migrations.RemoveField(
            model_name='yksexamresult',
            name='min_score_3',
        ),
        migrations.RemoveField(
            model_name='yksexamresult',
            name='min_score_4',
        ),
        migrations.RemoveField(
            model_name='yksexamresult',
            name='min_score_5',
        ),
        migrations.RemoveField(
            model_name='yksexamresult',
            name='yerlesen_1',
        ),
        migrations.RemoveField(
            model_name='yksexamresult',
            name='yerlesen_2',
        ),
        migrations.RemoveField(
            model_name='yksexamresult',
            name='yerlesen_3',
        ),
        migrations.RemoveField(
            model_name='yksexamresult',
            name='yerlesen_4',
        ),
        migrations.RemoveField(
            model_name='yksexamresult',
            name='yerlesen_5',
        ),
        migrations.AddField(
            model_name='useractivitysuggestion',
            name='analysis_type',
            field=models.CharField(choices=[('daily', 'Günlük'), ('weekly', 'Haftalık'), ('mock', 'Deneme')], default='daily', max_length=50),
        ),
        migrations.AddField(
            model_name='useractivitysuggestion',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='useractivitysuggestion',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='suggestions', to='api.usermodel'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='usermodel',
            name='goal',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='yksexamresult',
            name='max_score',
            field=models.FloatField(blank=True, null=True, verbose_name='En Büyük Puan'),
        ),
        migrations.AddField(
            model_name='yksexamresult',
            name='min_score',
            field=models.FloatField(blank=True, null=True, verbose_name='En Küçük Puan'),
        ),
        migrations.AlterField(
            model_name='yksexamresult',
            name='university_type',
            field=models.CharField(max_length=100, verbose_name='Üniversite Türü'),
        ),
        migrations.CreateModel(
            name='LessonData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lesson_name', models.CharField(max_length=100)),
                ('true_answers', models.IntegerField()),
                ('false_answers', models.IntegerField()),
                ('clear_answers', models.FloatField()),
                ('total_answers', models.IntegerField()),
                ('date', models.DateTimeField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lesson_data', to='api.usermodel')),
            ],
        ),
        migrations.DeleteModel(
            name='DailyReportModelAYT',
        ),
        migrations.DeleteModel(
            name='DailyReportModelTYT',
        ),
        migrations.DeleteModel(
            name='ResultModel',
        ),
    ]
